title: Chun-Li SF6 Docs
description: Collection of notes and documentation for Chun-Li in Street Fighter 6.
theme: just-the-docs

url: https://gr8stalin.github.io/chun-li-sf6-docs/

aux_links:
  Github Repository: https://github.com/gr8stalin/chun-li-sf6-docs

color_scheme: chun